### ISSUE TITLE
<link> and <script> assets

### ISSUE THREAD

**Issue by ssx** [lvarayut/assets-crawler#2]
Hi!

Will this crawler pull out any CSS files included via <link> tags and also <script> tags too?

Didn't seem to be included in my first test run, only images.

**Comment by lvarayut** [comment]
Hey!, it should include CSS, JS, and images files. Could you show me your example?

**Comment by ssx** [comment]
Hi!

https://dor.ky - plenty of CSS files,

```
node node_modules/assets-crawler/cli.js https://dor.ky > output.json
cat output.json | grep css
```

**Comment by ssx** [comment]
@lvarayut any ideas on this? :)

**Comment by lvarayut** [comment]
You could also put the `debug` flag to see errors while fetching, `assets-crawler --debug true https://dor.ky > output.json`. Most of the pages return `502` from the server. That's why it doesn't get any JS and CSS files. 

`assets-crawler` normally gets those files, for example, `assets-crawler https://facebook.github.io/relay`, this will return many JS and CSS files.

**Comment by ssx** [comment]
I'll certainly do that, thank you for the help!

**Comment by lvarayut** [comment]
You're very welcome :)

**Comment by ssx** [comment]
Quite odd, not sure what is causing it to 502, if I mirror with `wget` it will happily crawl the entire site.

Secondly, there are css <link> and some <script> tags in the index page, so I'd think those would come through in the crawled links but they don't.

Very bizarre. I do see the 502's when running with `--debug` too.
